name: Completion

on:
  workflow_dispatch:

jobs:
  completion:
    uses: jgutierrezdtt/security-tutorial-base/.github/workflows/reusable-completion.yml@main
    with:
      tutorial-name: SAST OpenGrep Professional
    secrets:
      token: ${{ secrets.GITHUB_TOKEN }}
